# Generated by Django 4.2.7 on 2024-01-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_email_verified_user_ver_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ver_code',
            field=models.CharField(default='012796676544', max_length=15, verbose_name='Проверочный код'),
        ),
    ]
