# Generated by Django 4.2.7 on 2023-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='views',
        ),
        migrations.AddField(
            model_name='blogs',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
