# Generated by Django 4.2.7 on 2023-12-25 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_date_of_creation_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 6, 3, 25, 282728), verbose_name='Дата создания'),
        ),
    ]
