# Generated by Django 4.2.7 on 2024-01-16 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_is_published_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('product_published', 'Can publish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 19, 43, 48, 419344), verbose_name='Дата создания'),
        ),
    ]
