# Generated by Django 4.2.7 on 2024-01-16 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_options_alter_product_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 22, 26, 8, 852530), verbose_name='Дата создания'),
        ),
    ]
